# This is a basic workflow to help you get started with Actions

name: black and flake8

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # checkout repo, setup python 3.9, install poetry preview
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-preview: true
      - run: poetry --version

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run black
        run: poetry run black .

      - name: Run flake8
        run: poetry run flake8
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # checkout repo, setup python 3.9, install poetry preview
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-preview: true
      - run: poetry --version

      - name: Install dependencies
        run: poetry install --with dev
      - name: Get SpaCy model
        run: poetry run python -m spacy download en_core_web_sm
      - name: Get corefree model
        run: poetry run python -m coreferee install en

      - name: Run tests
        run: poetry run pytest
